terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
bash: line 7: 21110 Aborted                 (core dumped) ./a.out
