terminate called after throwing an instance of 'std::runtime_error'
  what():  Lol bruh.
bash: line 7: 10080 Aborted                 (core dumped) ./a.out
