terminate called after throwing an instance of 'std::runtime_error'
  what():  
bash: line 7: 26584 Aborted                 (core dumped) ./a.out
